Fix broken C++ link in TOC
dafny-lang/dafny-lang.github.io pull request #15
Opened 2022-12-15 21:39 UTC by Timmmm

There's no `Compilation/Cpp` page, however there is a `Compilation/Boogie` page which isn't already linked so I changed it to that.

2022-12-20 15:40 UTC, MikaelMayer requested changes

2022-12-20 15:40 UTC, MikaelMayer commented on latest/toc.md
> +   * [Boogie](Compilation/Boogie)
Thanks for spotting this dead link ! However, the content of the cpp.md file was moved here:
https://dafny.org/latest/DafnyRef/DafnyRef#2587-c

it's lacking a permanent identifier. Would you be willing to go the extra mile and add the correct link with a permanent identifier?

2022-12-20 15:42 UTC, davidcok commented
I'll take this on. Note that we no longer merge PRs directly into this repo. We do them on dafny-lang/dafny and snapshot the documentation when new versions are released.

2022-12-23 18:52 UTC, davidcok commented
Fixed with https://github.com/dafny-lang/dafny/pull/3266
though it won't be fixed on dafny.org until a new release is published

2022-12-23 18:52 UTC, closed without merging