Establishing versioned snapshots of documentation
dafny-lang/dafny-lang.github.io pull request #3
Opened 2022-09-24 13:39 UTC by davidcok

This PR and the companion PR in dafny-lang/dafny puts in place the structure for user documentation:

dafny.org -> snapshot of docs at time of latest release
dafny.org/V-x.y.z -> snapshot of docs at time of release x.y.z
dafny.org/dafny -> current development docs (i.e. bleeding edge)

There are links on various pages to enable navigation. Except for a few links of this sort, these are just deep copies of docs.

In a future PR I will 
- automate the process of creating snapshots as part of the release
- attempt to change the dafny.org/dafny URL to something better, such as dafny-dev.org or dafny.org/dev. This will likely require DNS record changes.

2022-09-26 18:05 UTC, robin-aws requested changes
The layout LGTM (except for my comments here: https://github.com/dafny-lang/dafny/pull/2798#discussion_r980339854)

I think this is a great PR in which to add a README.md describing that layout though, and to clarify that from this point on the contents of this repo will ONLY be snapshots. Probably worth stating that if anyone finds issues to reach out to us through `dafny-lang/dafny` instead.

2022-09-26 18:52 UTC, davidcok commented
You previously did not want a version label on the top-level landing page (the latest release snapshot), but having one would emphasize that this is a snapshot, especially since before this change it was not a snapshot. Should I add that version label back?

2022-09-26 18:58 UTC, robin-aws commented
I think I'd still prefer no label. From an end-user's perspective the fact that the content happens to be a snapshot of `dafny-lang/dafny/docs` updated on each Dafny release isn't really that relevant to their experience.

2022-09-26 19:06 UTC, robin-aws requested changes
Oof, having the README.md file is great but now I realize it pollutes the top-level snapshot with an extra file (and in fact conflicts with the existing `docs/README.md` file in `dafny-lang/dafny`). Is there any way to have the latest snapshot served from the top-level `dafny.org` URL but persisted in a subdirectory instead?

2022-09-26 19:06 UTC, robin-aws commented on README.md
> +The current development work and git history of documentation is in the `dafny-lang//dafny` repository, in the `docs`
```suggestion
The current development work and git history of documentation is in the `dafny-lang/dafny` repository, in the `docs`
```

2022-09-26 19:06 UTC, robin-aws commented on README.md
> +There are also links (at `https://dafny.org/snapshots) to all of the past snapshots since this process began (with v3.8.2).
```suggestion
There are also links (at `https://dafny.org/snapshots`) to all of the past snapshots since this process began (with v3.9.0).
```

2022-09-26 19:14 UTC, davidcok commented
Yes, it is possible, I think -- by putting a redirect for index.html at the top-level that redirects to the latest version folder.
If you want to adopt that solution, I'll need a bit of time to experiment with it to make sure it works, at least in preview mode.

2022-09-27 17:00 UTC, davidcok commented
Here is an alternate design: Have just the landing page (and necessary alternate files) at the top-level. All version snapshots are in vX.Y.Z subfolders. There is also a `latest` link that redirects to the most recent version. This makes a parallel structure. The problem is that the current version shows up in the URL, not 'latest', which I think is undesirable. We could have `latest` have its own copy, updated upon each version. Then the user would see URLs like dafny.org/latest/tutorials and dafny.org/latest/DafnyRef/DafnyRef . If we don't mind the ubiquitous `latest`, this would work easily. Otherwise we stick with what we have.

2022-09-27 17:41 UTC, robin-aws commented
I definitely like the idea of just the landing page at the top level, and no snapshotted files. I suppose that means that content would be maintained in this repo instead of copied over from `dafny-lang/dafny` during the release process, but I'd be fine with that. I agree having `latest` in the URL would be nice but I'm not as concerned about that if it turns out to be a hassle.

2022-09-27 18:08 UTC, davidcok commented
We would still maintain the active development in dafny-lang.dafny. I'll prepare an alternate draft PR with this scheme, with a v3.9.0-draft.

2022-09-29 15:48 UTC, merged